### PR TITLE
Bump frontend to 20240620075826

### PR DESCRIPTION
**Pull request by ludeeus**

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by ludeeus** [comment]
And OFC there are more deprecated things in core...

**Comment by frenck** [comment]
> And OFC there are more deprecated things in core...

Oh that one is new indeed, but that will take a long time still 2025.7

**Comment by ludeeus** [comment]
True, but as the tests here are the way they are, I need to fix that before they can pass.
It's just been a trend lately; every week, something is deprecated.

**Comment by ludeeus** [comment]
Thanks for the approval @frenck 🥇

**Pull request merged**
