### PR TITLE
Avoid creating async_register_repository tasks to register_unknown_repositories

### LINKED ISSUE #3535: A flood of async_register_repository tasks gets created at startup which slows down the event loop
### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

A flood of async_register_repository tasks gets created at startup which slows down the event loop

### Reproduction steps

restart

### Debug logs

```text
2024-02-29 23:04:37.856 WARNING (MainThread) [asyncio.base_events] Create task: <coroutine object HacsBase.async_register_repository at 0x7f307148a200> - None
2024-02-29 23:04:37.857 WARNING (MainThread) [asyncio.base_events] Create task: <coroutine object HacsBase.async_register_repository at 0x7f307148ae80> - None
2024-02-29 23:04:37.857 WARNING (MainThread) [asyncio.base_events] Create task: <coroutine 
...
```

snip to fix in 65536 limit, it goes on an on
Screenshot 2024-03-01 at 10 17 50 AM

### Diagnostics dump

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
Await these in series to avoid creating tasks as they are unlikely to suspend.

fixes #3535

### CODE REVIEW

**Comment by bdraco** [comment]
first call takes 0.00011390098370611668s
second call and after take 3.6492012441158295e-05

await in series seems like a better option here

**Comment by bdraco** [comment]
need to do a fresh install to make sure this is ok

**Comment by ludeeus** [comment]
> need to do a fresh install to make sure this is ok

if you do that you should tick the last box in the flow to enable experimental not to give yourself a GitHub rate limit break 😄

**Comment by bdraco** [comment]
This works well on a fresh install as well

**Review by ludeeus — APPROVED** [review]
Thanks 👍 

I'm currently in the process of changing things around with actions and testing, so If you do not mind I will leave it as-is (open) until that is complete so this can be run against that as well.

It will still go in the next version.

**Comment by bdraco** [comment]
Its been a problem for years and we have lived with it so no rush at all.

**Comment by bdraco** [comment]
Screenshot 2024-03-02 at 2 23 22 PM

All the time is spent on line 30

**Comment by bdraco** [comment]
constructing enums can be oddly slow because they are singletons that have to find the object

maybe

```diff
diff --git a/custom_components/hacs/repositories/integration.py b/custom_components/hacs/repositories/integration.py
index 70b8b547..72fe5f6b 100644
--- a/custom_components/hacs/repositories/integration.py
+++ b/custom_components/hacs/repositories/integration.py
@@ -18,6 +18,7 @@ from .base import HacsRepository
 if TYPE_CHECKING:
     from ..base import HacsBase
 
+CATEGORY_INTEGRATION = HacsCategory.INTEGRATION
 
 class HacsIntegrationRepository(HacsRepository):
     """Integrations in HACS."""
@@ -27,7 +28,7 @@ class HacsIntegrationRepository(HacsRepository):
         super().__init__(hacs=hacs)
         self.data.full_name = full_name
         self.data.full_name_lower = full_name.lower()
-        self.data.category = HacsCategory.INTEGRATION
+        self.data.category = CATEGORY_INTEGRATION
         self.content.path.remote = "custom_components"
         self.content.path.local = self.localpath
 
```

**Comment by ludeeus** [comment]
That will eventually be set as a class instead of an instance attribute.
That will be a better saving than doing this.

**Pull request merged**
