### PR TITLE
Simplify startup logic

### LINKED ISSUE #2005: Startup is still blocked (just later on)
Well I thought we had ironed this out 🤕 , but after https://github.com/home-assistant/core/pull/48274 I sorted out everything else that was blocking startup and realized, `hacs` was still blocking startup.

I'm going to try to find some time this weekend to dig in more, but I wanted to open this so I didn't forget.

```
2021-04-03 20:42:34 DEBUG (MainThread) [homeassistant.core] Waited 1 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a2235b0>()]>>
2021-04-03 20:42:35 DEBUG (MainThread) [homeassistant.core] Waited 2 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:36 DEBUG (MainThread) [homeassistant.core] Waited 3 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:37 DEBUG (MainThread) [homeassistant.core] Waited 4 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:38 DEBUG (MainThread) [homeassistant.core] Waited 5 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:39 DEBUG (MainThread) [homeassistant.core] Waited 6 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:40 DEBUG (MainThread) [homeassistant.core] Waited 7 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:41 DEBUG (MainThread) [homeassistant.core] Waited 8 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb02a232a00>()]>>
2021-04-03 20:42:42 DEBUG (MainThread) [homeassistant.core] Waited 9 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb029e15280>()]>>
2021-04-03 20:42:43 DEBUG (MainThread) [homeassistant.core] Waited 10 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb029e15280>()]>>
2021-04-03 20:42:44 DEBUG (MainThread) [homeassistant.core] Waited 11 seconds for task: <Task pending name='Task-4714' coro=<Hacs.startup_tasks() running at /config/custom_components/hacs/hacsbase/hacs.py:161> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7fb029e15280>()]>>
```

### PR DESCRIPTION
**Pull request by bdraco**
- Ensure startup_tasks run after EVENT_HOMEASSISTANT_STARTED when restarting

Fixes #2005

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
Looks cleaner, but it does not really change anything? how is this fixing #2005 ?

**Comment by bdraco** [comment]
config_type was always flow at startup so it would never got to the else which meant even thought we were not at running yet it would always use the call later logic.

**Comment by ludeeus** [comment]
But `config_type` is not always "flow"? if it is, that's a bug, it should be "yaml" when you configure with YAML.

**Comment by bdraco** [comment]
> But `config_type` is not always "flow"? if it is, that's a bug, it should be "yaml" when you configure with YAML.

It is `flow` if setup from the UI, and `yaml` if coming from `yaml`.

I think we don't want to delay startup regardless of it being `yaml` or `flow`???

Sorry for the lack of clarity.

**Comment by bdraco** [comment]
Any chance this could go out before beta? I'd like to get feedback on some of the startup performance improvements and this will cloud some of the profiles users will send.

**Comment by ludeeus** [comment]
There are a few more things that needs to get out, so will be with those, most likely on Sunday

**Pull request merged**
