### PR TITLE
Revert the UI back to use the old way

### LINKED ISSUE #1183: Separate new repo notifications from installed components
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
The new page layout feels a little confusing and if you have a lot of custom additions new repos may be missed if they are further down.  

## Implementation
Move the newly added repos to their own tab which would only be shown if new repos exist.   This keeps the installed features pages clean whilst allowing you to look at the new repos when you have time rather than when you have gone in to do something else. 

## Alternatives

Surface new repos at the top of the page with your installed ones below as per the old installs page.

### LINKED ISSUE #1185: Use paper-dialog-background-color for pop up card background in v1.0.0
## Category
- [x] Frontend

## The idea
Use `paper-dialog-background-color` for the background of the pop up cards in v1.0.0. It is the same theme element that the rest of the HA pop up cards use for their background. This will help people that use transparent themes be able to read the cards.

## Example
Not using `paper-dialog-background-color`
image

Using `paper-dialog-background-color`
image

### LINKED ISSUE #1188: Make add repository button more accessible
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
To install a new integration, cards, ... we need to scroll to the bottom of the add repository pop up to be able to see buttons 

Button need to be more visible and more accessible 

## Implementation

I have though about several options:

- duplicate button in the header (inside a three dot button for example)
- make the footer always visible (fixed). Only the content is scrollable

I think the second one is what I prefer ...

## Additional context

image

### LINKED ISSUE #1189: Display only relative package on add repository pop up
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
It feel weird to me that we have tabs for integration and front-end but when adding a repository we see all types

I expect when I am in integration and click on +, to see only integrations
same for front-end ...

## Implementation

Only display packages relative to the current tab
If in integrations tabs, show only integrations
If in front-end tabs, show only cards and theme

## Alternatives

Are there any alternative solutions or features you've considered?

in the material design guideline about [buttons floating action button](https://material.io/components/buttons-floating-action-button#types-of-transitions), we can open sub-button like

image

On click on the add button, we could display different type of package type: integration, cards, themes, ... and the pop up only display the selected type

### LINKED ISSUE #1193: list all the items except one all ready installed
-  Frontend

## The idea
the message "Only the first 100 repositories are shown, use the search to filter what you need"
is silly how do I know what to search for 

I want a full list so I can see what I can do  - then I will go out and buy that item because I know hacs has the items to deal with it 

## Implementation

as set of pages that list the full title information and basic summary  with high lights on new and already installed   plus version info so I can see if updated ones are a major or minor update  and so I can see which one are beta

## Alternatives

just give back the old version  as an option that covered all this info and just need a little style refresh

### LINKED ISSUE #1196: Add preview/screenshot browsing for themes
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea

it s kinda hard to find a good theme without installing it , adding a theme gallery would be a nice feature
## Implementation

- adding a required screenshot of the theme in the theme's repo
- create a gallery view to access the theme's description/install prompt

### LINKED ISSUE #1208: Keep the search bar shown on top
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea

Keep the search bar shown on top while scrolling through repositorys and keep the window the same width while typing in the search bar.

### LINKED ISSUE #1210: Freezes when scrolling down to install anything
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0.1
Home Assistant version         | 0.110.0
Installation method for HA    | Docker
Web browser                         | Chrome, Firefox, iOS app
Web browser version            |

## Checklist

- [x ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read https://hacs.xyz/docs/issues
- [x ] This issue is related to the frontend of HACS.

## Describe the issue

A clear and concise description of what the issue is.
If I scroll down on any integration/card it freezes and I am unable to install anything

### Steps to reproduce

1. Click on an intrgration, such as Custom Header
2. Scroll down to install
3. HACS freezes, can only click back to overview or any other HA tabs, but HACS is locked up.

### LINKED ISSUE #1212: Add integration type tag to installed cards
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Cards should have a tag on what they are. I'm in the Frontend tab and I see plugins next to themes but it's not easy to decipher what they are: 
image

### LINKED ISSUE #1213: Install latest version when clicking install.
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Clicking install on a new theme brings me a modal in a modal to select the version, let's just install the latest version!!! 
image

### LINKED ISSUE #1216: Highlight newly released integrations
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

How do I know about newly released integrations? I kinda liked the old ui in this respect (I learned about newly released integrations.

### LINKED ISSUE #1218: Update Information functionality
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea
 I'm not sure what update information here does: 
image. I'm assuming refreshes metadata, not sure that should be the first item?

Maybe we just refresh the repository data when you click on the information menu item?

### LINKED ISSUE #1219: Add ability to sort repositories in Add dialog
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea
The add dialog should be default sorted by most popular, with a dropdown for sorting by most downloaded, recently updated, name.

### LINKED ISSUE #1223: Show more than the first 100 repositories
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Extracted from #1194 

"Only the first 100 repositories are shown, use the search to filter what you need". This is a hit to discoverability. It wouldn't be that big of a problem if there were filtering and sorting options, but as it is, some repositories will just never be shown.

For example, at least on my install, button-card is the second to last repository. This is one of the most popular and useful repositories IMO. It wouldn't be good if it isn't visible. Maybe users won't think to search for "button" - there already is a button at the end of the day, why would they need that?

## Implementation

Consider adding dynamic loading on scroll or pagination to the list.

### LINKED ISSUE #1224: Show available repositories by default
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Extracted from #1194

I don't know if that's true for most users, but my 2 main use cases for HACS are: 1. updating installed repositories (handled on the Home page), and 2. browsing/installing new repositories. 

Dedicating so much space for currently installed repositories looks good and is consistent with HA's Integrations page, but is less useful IMO.

## Implementation

Consider making the list of available repositories a first-level citizen instead of it being hidden in a popup. 

To me, the discovery/exploration part of HACS is the most-important use-case (both as a user and as a contributor). Seeing the list of your already installed repositories that don't even have an update is a secondary job IMO.

I would experiment with showing available repositories in each page and showing the installed ones in a popup.

## Alternative

Show all repositories in their respective pages. Group installed ones at the top, show all others after that. 

If there is search/filter/sort it can apply to all repositories per-group. E.g. if you sort by stars, it will first show the installed group sorted by stars, then the available group sorted by stars.

### LINKED ISSUE #1225: Set a fixed popup width
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Extracted from #1194

Searching changes the popup width:

## Implementation

Consider setting a fixed width for the popup.

### LINKED ISSUE #1226: Indicator whenever plugin is added to Lovelace.
## Category
  * [ ]  Backend/Integration
  * [x]  Frontend
  * [ ]  Documentation
  * [ ]  Bot
  * [ ]  Other

## Checklist
  * [x]  This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

The plugin types in Frontend card should have visual indicator whenever they are added to Lovelace resources.
HACS_v1 0_missing_resouce_indicator

It would be nice if there was an option to (re)add Lovelace plugins from HACS like in v0.24.
HACS_v1 0_add_to_lovelace_prompt

### PR DESCRIPTION
**Pull request by ludeeus**
Due to popular? opinion I'm making this PR to bring back the old UI.
image

This will also bring back all the issues it was with that UI, and I will only do bugfixes from this point in the UI, you can still add feature requests but I will not be adding them.

The reasons I changed it in the first place:
- It was falling behind HA, in how it felt to use and I wanted to bring it closer.
- It has performance issues, and those will continue to grow with each new repository that is added.
- The codebase are hard to maintain, there are elements all over the place that somehow ties together.

There has been a great number of feature requests added for the new UI, I will pause the work on them until this is decided.

closes #1226, closes #1225, closes #1224, closes #1223, closes #1219, closes #1218, closes #1216, closes #1213, closes #1212, closes #1210, closes #1208, closes #1196, closes #1193, closes #1189, closes #1188, closes #1185, closes #1183

Frankly, I'm just too tired with all the negativity...

So add your votes on this description:
👍 Merge this.
👎 Keep working on the new UI.

### CODE REVIEW

**Comment by goliath2k** [comment]
Please keep working on the new UI, specially because of performance, just what is installed needs to be solved.

**Comment by scooper1** [comment]
i think the new will be good - just some ideas that needed more sorting
There was nothing publish to say problems with old ui
It may have been better to post this updated UI as a release candidate   and let people get more used to it
It was pushed as a release that did the original functions better - internally this is true but interface looked like it was missing a lot of functionality but in fact it good but needs a little tweaking  and for us to get heads around a new way of doing things  

I am getting more used to it 

well done on doing the code but a slower release would have put  the dreaded users in a more accepting mindset

**Comment by DavidFW1960** [comment]
Theres stuff about the new one I don't like (no table view, new repos not grouped, Plugins and Themes should be seperate) but I would never have started a thread to bitch about it. There's only one way to go and that is forward, not back.

**Comment by ugleatle** [comment]
While i understand that performance and reasonable code mus be prioritized, the new UI was more difficult to use and less feature-rich IMHO, no matter how it moves forward, new or old. I really hope the liste of installed custom components is kept.

**Comment by NovaGL** [comment]
The new UI is really hard to use, I don't know where anything is or what to do.

Is it possible for users to choose? The old version was much more intuitive

**Comment by renewoensdregt** [comment]
There is some real good stuff about the new one, so as others say, move forward and add some requests. What I personally liked about the old is that you could see the entire repository abs discover new things. With the limit to 100 and not setting new things, we have to discover new features in another way. 

Thumbs up for the great work! HACS make s life so much easier!!

**Comment by aidbish** [comment]
Hell no Ludeeus, keep going forward. Please do not revert

Also please do not entertain the idea of having both layouts and the user choose which to use, you know this will still have the issues described above and just create additional effort from you.

**Comment by Dinth** [comment]
I think that the new UI was not yet ready to go replace the main one, but since its already there, instead of reverting it, its better to focus on fixing its usability.
The new UI is genuinely prettier than the old one, the only problems is in its ergonomics, but since you say that the new UI codebase is way easier to maintain, it should be a big struggle to fix the issues people are having.

**Comment by DanielPiccoli** [comment]
how the hell do i downgrade back ?
lost ability to downgrade an installed component   <<   gigantic miss ??
UI glitch problems where the page can't decide between 4 or 5 columns, i have seen my screen shift between the 2 constantly for no reason
when i install a component, it does not tell me to add it to lovelace, HOLY SHIT, this is a HUGE required - i don`t know why someone would scrap that.

**Comment by aidbish** [comment]
> how the hell do i downgrade back ?
> lost ability to downgrade an installed component << gigantic miss ??
> UI glitch problems where the page can't decide between 4 or 5 columns, i have seen my screen shift between the 2 constantly for no reason
> when i install a component, it does not tell me to add it to lovelace, HOLY SHIT, this is a HUGE required - i don`t know why someone would scrap that.

Apart from being ungrateful, maybe take time to learn how to use it before whining.
You dont need to know how to add to lovelace, it does it for you, add a card, go to lovelace dashboards, resources. look its there. magic hey?

go back to another version of, uninstall, install, select version. - easy

downgrade - HACS, maybe uninstall it and walk away

**Comment by tomlut** [comment]
I've changed my mind. I was going to say go back but instead just I think there's room for improvement with the new UI. 

It was a lot easier to browse integrations and plugins with the previous version. And I liked the separation between installed and new. 

The new version does seem to be more responsive though.

**Comment by s2d4** [comment]
The new UI is so much faster. I thought it got faster on my lenovo tiny so I went checking on my Rpi backup and it was even more noticeable on it. 

Definitely stick with the new, improve from there and never look back.

**Comment by sembeeuk** [comment]
I am going to disagree with the majority of the above posts, and say that you should revert back to the old way as an interim step. 

Stop development on the old interface by all means, but it should be put back as soon as possible so that you don't lose the goodwill of the many 1000s of users while you sort out the issues with it. 
I will not disagree that it has its flaws and an update is required, but, being blunt, you went about it the wrong way. 
There was no warning, there is no feature parity and it felt like it was forced because most users of your tool have got used to seeing updates which do not affect how it works in such a fundamental way, and have therefore just got used to doing the updates as they are offered. 
The timing also didn't help, as it coincided with the recent release of HA 110 which required most of the components stored within HACS to be updated and therefore a lot of people who might not have updated immediately, did so because it was just part of the list and felt that it would be required to ensure support with HA 110. 

You also probably should realise the key part that HACS now plays within the wider HA ecosystem. For a significant number of users it is the only way that non-standard components are added to their HA install, and for developers of those components it is the only way they get any visibility or significant numbers of users, with the chance that their component will be pulled in to the main product. To quote a famous film - "With great power comes great responsibility" - any changes you make to the tool will have a significant impact on a lot of users. 

Therefore I would suggest that you do something similar to this.

1. Revert back to the old interface, stating quite clearly that development of it has stopped unless a show stopper/security bug is found. 
If you really do not want to do that, then provide details on how to revert manually. 
2. Start an open BETA program of the new interface, with the primary aim to get feature parity before a 1.0 release. If you want to introduce new functionality, do it after you have got feature parity of the old version. 
3. When you are ready to release the new version, have a period of dual running, so that those who were not on the BETA can test it and you can iron out any last minute issues. Then switch the code. 

That should keep most people happy, rescue a situation which has caused a lot of upset within the HA community and allow you to move in the direction that you wish to.

**Comment by SeanPM5** [comment]
> it felt like it was forced because most users of your tool have got used to seeing updates which do not affect how it works in such a fundamental way, and have therefore just got used to doing the updates as they are offered.

Nobody was forced into doing anything. If someone blindly updated HACS without reading, that's entirely their fault. The [release notes](https://github.com/hacs/integration/releases/tag/1.0.0) had a screenshot of the brand new UI and literally the first two bullet points were "Brand new UI!" and "Breaking changes!"

Did you not even notice that the version number jumped from 0.24.5 all the way up to 1.0.0? It should be obvious just from that alone to expect major changes.

Things are rarely ever 100% perfect on the first revision, but people like @GeorgeSG are providing detailed and constructive feedback in a positive way. That's far more helpful than asking for it to be reverted.

**Comment by aidbish** [comment]
I love these comments of being forced, nobody forced you, you clicked update/upgrade, you nobody else. Instead of blindly updating without even checking anything and that applies to HA also, you only have yourself to blame.

**Comment by NovaGL** [comment]
We need to stop this blame game. It's not helpful to anyone.

There are people who are passionate for keeping the change and people who are passionate for reverting. Each view should be respected and people allowed to have their own opinion.

I think ultimately in the long run we have to keep with the new UI, but in the mean time I believe things need to change.

Educating people is the way to resolve this in my opinion.

I believe if we are keeping the new UI we need to have a "first launch" screen.
This screen will be displayed one time when people load to tell them about the changes and help them answer FAQ.

Eg you do not need to click add to lovelace anymore frontend changes are automatically added to the lovelace configuration.

Then we can go on to improving the new UI to 'fix' things that are missing.

- I think there should be a separate tab for custom repositories that way we can easily add or remove additional repositories. I find it's currently to hidden under the three dots at the top right.
- The old version gave you an indication when you were installing repos that something was happening, now you just get a blank screen.
- In the future you could look at adding views as I find the cards are too big, in the old version they were much smaller.

I can understand the goal is to make it look as consistent as possible with the rest of the UI, so we're on the right track just need to work on refining things.

Keep up the good work!

**Comment by DavidFW1960** [comment]
> We need to stop this blame game. It's not helpful to anyone.

The fact that the dev was feeling beaten down enough to consider reverting - begs to differ.
If you don't like it then offer constructive feedback.
The dev is not your bitch and he does not owe you anything. Try being grateful.

**Comment by ludeeus** [comment]
Thanks for all the feedback.
With a 10/42 split, I'm closing this and will start implementing feature requests with the new UI.

If you have ideas not covered with the current pool of feature requests please open them.

**Pull request closed without merging**
