### PR TITLE
Reduce memory required for logger

### PR DESCRIPTION
**Pull request by bdraco**
Similar to https://github.com/home-assistant/core/pull/42894

### CODE REVIEW

**Comment by ludeeus** [comment]
It has a fixed number of instances, so it's not a leak?

**Comment by bdraco** [comment]
> It has a fixed number of instances, so it's not a leak?

Right. I'll adjust the title as its really about reducing the number of logger objects in memory in this case as new repos are added they increase over time.

**Comment by ludeeus** [comment]
There is not really a good reason to have so many, it easy to identify, but that can be done with variables as well, i should not need more than 1-10 different instances.

Will clean that some other time (actually thought about that earlier today)

**Review by ludeeus — APPROVED** [review]
Thanks!

**Pull request merged**
