### PR TITLE
Add devcontainer features to dependabot

### PR DESCRIPTION
**Pull request by tjorim**
I don't use devcontainers myself yet but was requested in https://github.com/hacs/addons/pull/12.

### CODE REVIEW

**Comment by tjorim** [comment]
While this will handle dependency updates I'm not sure if this label is the correct one.

**Comment by tjorim** [comment]
While this will handle dependency updates I'm not sure if this label is the correct one.
@coderabbitai what do you think?

**Comment by tjorim** [comment]
@coderabbitai retry

**Review by ludeeus — APPROVED** [review]
Thanks 👍

**Pull request merged**
